// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lvm.proto

package lvm

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogicalVolume_Attributes_Type int32

const (
	LogicalVolume_Attributes_MALFORMED_TYPE               LogicalVolume_Attributes_Type = 0
	LogicalVolume_Attributes_MIRRORED                     LogicalVolume_Attributes_Type = 1
	LogicalVolume_Attributes_MIRRORED_WITHOUT_SYNC        LogicalVolume_Attributes_Type = 2
	LogicalVolume_Attributes_ORIGIN                       LogicalVolume_Attributes_Type = 3
	LogicalVolume_Attributes_ORIGIN_WITH_MERGING_SNAPSHOT LogicalVolume_Attributes_Type = 4
	LogicalVolume_Attributes_RAID                         LogicalVolume_Attributes_Type = 5
	LogicalVolume_Attributes_RAID_WITHOUT_SYNC            LogicalVolume_Attributes_Type = 6
	LogicalVolume_Attributes_SNAPSHOT                     LogicalVolume_Attributes_Type = 7
	LogicalVolume_Attributes_MERGING_SNAPSHOT             LogicalVolume_Attributes_Type = 8
	LogicalVolume_Attributes_PV_MOVE                      LogicalVolume_Attributes_Type = 9
	LogicalVolume_Attributes_VIRTUAL_MIRROR               LogicalVolume_Attributes_Type = 10
	LogicalVolume_Attributes_VIRTUAL_RAID_IMAGE           LogicalVolume_Attributes_Type = 11
	LogicalVolume_Attributes_RAID_IMAGE_OUT_OF_SYNC       LogicalVolume_Attributes_Type = 12
	LogicalVolume_Attributes_MIRROR_LOG                   LogicalVolume_Attributes_Type = 13
	LogicalVolume_Attributes_UNDER_CONVERSION             LogicalVolume_Attributes_Type = 14
	LogicalVolume_Attributes_THIN                         LogicalVolume_Attributes_Type = 15
	LogicalVolume_Attributes_THIN_POOL                    LogicalVolume_Attributes_Type = 16
	LogicalVolume_Attributes_THIN_POOL_DATA               LogicalVolume_Attributes_Type = 17
	LogicalVolume_Attributes_RAID_OR_THIN_POOL_METADATA   LogicalVolume_Attributes_Type = 18
)

var LogicalVolume_Attributes_Type_name = map[int32]string{
	0:  "MALFORMED_TYPE",
	1:  "MIRRORED",
	2:  "MIRRORED_WITHOUT_SYNC",
	3:  "ORIGIN",
	4:  "ORIGIN_WITH_MERGING_SNAPSHOT",
	5:  "RAID",
	6:  "RAID_WITHOUT_SYNC",
	7:  "SNAPSHOT",
	8:  "MERGING_SNAPSHOT",
	9:  "PV_MOVE",
	10: "VIRTUAL_MIRROR",
	11: "VIRTUAL_RAID_IMAGE",
	12: "RAID_IMAGE_OUT_OF_SYNC",
	13: "MIRROR_LOG",
	14: "UNDER_CONVERSION",
	15: "THIN",
	16: "THIN_POOL",
	17: "THIN_POOL_DATA",
	18: "RAID_OR_THIN_POOL_METADATA",
}

var LogicalVolume_Attributes_Type_value = map[string]int32{
	"MALFORMED_TYPE":               0,
	"MIRRORED":                     1,
	"MIRRORED_WITHOUT_SYNC":        2,
	"ORIGIN":                       3,
	"ORIGIN_WITH_MERGING_SNAPSHOT": 4,
	"RAID":                         5,
	"RAID_WITHOUT_SYNC":            6,
	"SNAPSHOT":                     7,
	"MERGING_SNAPSHOT":             8,
	"PV_MOVE":                      9,
	"VIRTUAL_MIRROR":               10,
	"VIRTUAL_RAID_IMAGE":           11,
	"RAID_IMAGE_OUT_OF_SYNC":       12,
	"MIRROR_LOG":                   13,
	"UNDER_CONVERSION":             14,
	"THIN":                         15,
	"THIN_POOL":                    16,
	"THIN_POOL_DATA":               17,
	"RAID_OR_THIN_POOL_METADATA":   18,
}

func (x LogicalVolume_Attributes_Type) String() string {
	return proto.EnumName(LogicalVolume_Attributes_Type_name, int32(x))
}

func (LogicalVolume_Attributes_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0, 0}
}

type LogicalVolume_Attributes_Permissions int32

const (
	LogicalVolume_Attributes_MALFORMED_PERMISSIONS LogicalVolume_Attributes_Permissions = 0
	LogicalVolume_Attributes_WRITEABLE             LogicalVolume_Attributes_Permissions = 1
	LogicalVolume_Attributes_READ_ONLY             LogicalVolume_Attributes_Permissions = 2
	LogicalVolume_Attributes_READ_ONLY_ACTIVATION  LogicalVolume_Attributes_Permissions = 3
)

var LogicalVolume_Attributes_Permissions_name = map[int32]string{
	0: "MALFORMED_PERMISSIONS",
	1: "WRITEABLE",
	2: "READ_ONLY",
	3: "READ_ONLY_ACTIVATION",
}

var LogicalVolume_Attributes_Permissions_value = map[string]int32{
	"MALFORMED_PERMISSIONS": 0,
	"WRITEABLE":             1,
	"READ_ONLY":             2,
	"READ_ONLY_ACTIVATION":  3,
}

func (x LogicalVolume_Attributes_Permissions) String() string {
	return proto.EnumName(LogicalVolume_Attributes_Permissions_name, int32(x))
}

func (LogicalVolume_Attributes_Permissions) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0, 1}
}

type LogicalVolume_Attributes_Allocation int32

const (
	LogicalVolume_Attributes_MALFORMED_ALLOCATION LogicalVolume_Attributes_Allocation = 0
	LogicalVolume_Attributes_ANYWHERE             LogicalVolume_Attributes_Allocation = 1
	LogicalVolume_Attributes_CONTIGUOUS           LogicalVolume_Attributes_Allocation = 2
	LogicalVolume_Attributes_INHERITED            LogicalVolume_Attributes_Allocation = 3
	LogicalVolume_Attributes_CLING                LogicalVolume_Attributes_Allocation = 4
	LogicalVolume_Attributes_NORMAL               LogicalVolume_Attributes_Allocation = 5
	LogicalVolume_Attributes_ANYWHERE_LOCKED      LogicalVolume_Attributes_Allocation = 6
	LogicalVolume_Attributes_CONTIGUOUS_LOCKED    LogicalVolume_Attributes_Allocation = 7
	LogicalVolume_Attributes_INHERITED_LOCKED     LogicalVolume_Attributes_Allocation = 8
	LogicalVolume_Attributes_CLING_LOCKED         LogicalVolume_Attributes_Allocation = 9
	LogicalVolume_Attributes_NORMAL_LOCKED        LogicalVolume_Attributes_Allocation = 10
)

var LogicalVolume_Attributes_Allocation_name = map[int32]string{
	0:  "MALFORMED_ALLOCATION",
	1:  "ANYWHERE",
	2:  "CONTIGUOUS",
	3:  "INHERITED",
	4:  "CLING",
	5:  "NORMAL",
	6:  "ANYWHERE_LOCKED",
	7:  "CONTIGUOUS_LOCKED",
	8:  "INHERITED_LOCKED",
	9:  "CLING_LOCKED",
	10: "NORMAL_LOCKED",
}

var LogicalVolume_Attributes_Allocation_value = map[string]int32{
	"MALFORMED_ALLOCATION": 0,
	"ANYWHERE":             1,
	"CONTIGUOUS":           2,
	"INHERITED":            3,
	"CLING":                4,
	"NORMAL":               5,
	"ANYWHERE_LOCKED":      6,
	"CONTIGUOUS_LOCKED":    7,
	"INHERITED_LOCKED":     8,
	"CLING_LOCKED":         9,
	"NORMAL_LOCKED":        10,
}

func (x LogicalVolume_Attributes_Allocation) String() string {
	return proto.EnumName(LogicalVolume_Attributes_Allocation_name, int32(x))
}

func (LogicalVolume_Attributes_Allocation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0, 2}
}

type LogicalVolume_Attributes_State int32

const (
	LogicalVolume_Attributes_MALFORMED_STATE                           LogicalVolume_Attributes_State = 0
	LogicalVolume_Attributes_ACTIVE                                    LogicalVolume_Attributes_State = 1
	LogicalVolume_Attributes_SUSPENDED                                 LogicalVolume_Attributes_State = 2
	LogicalVolume_Attributes_INVALID_SNAPSHOT                          LogicalVolume_Attributes_State = 3
	LogicalVolume_Attributes_INVALID_SUSPENDED_SNAPSHOT                LogicalVolume_Attributes_State = 4
	LogicalVolume_Attributes_SNAPSHOT_MERGE_FAILED                     LogicalVolume_Attributes_State = 5
	LogicalVolume_Attributes_SUSPENDED_SNAPSHOT_MERGE_FAILED           LogicalVolume_Attributes_State = 6
	LogicalVolume_Attributes_MAPPED_DEVICE_PRESENT_WITHOUT_TABLES      LogicalVolume_Attributes_State = 7
	LogicalVolume_Attributes_MAPPED_DEVICE_PRESENT_WITH_INACTIVE_TABLE LogicalVolume_Attributes_State = 8
)

var LogicalVolume_Attributes_State_name = map[int32]string{
	0: "MALFORMED_STATE",
	1: "ACTIVE",
	2: "SUSPENDED",
	3: "INVALID_SNAPSHOT",
	4: "INVALID_SUSPENDED_SNAPSHOT",
	5: "SNAPSHOT_MERGE_FAILED",
	6: "SUSPENDED_SNAPSHOT_MERGE_FAILED",
	7: "MAPPED_DEVICE_PRESENT_WITHOUT_TABLES",
	8: "MAPPED_DEVICE_PRESENT_WITH_INACTIVE_TABLE",
}

var LogicalVolume_Attributes_State_value = map[string]int32{
	"MALFORMED_STATE":                           0,
	"ACTIVE":                                    1,
	"SUSPENDED":                                 2,
	"INVALID_SNAPSHOT":                          3,
	"INVALID_SUSPENDED_SNAPSHOT":                4,
	"SNAPSHOT_MERGE_FAILED":                     5,
	"SUSPENDED_SNAPSHOT_MERGE_FAILED":           6,
	"MAPPED_DEVICE_PRESENT_WITHOUT_TABLES":      7,
	"MAPPED_DEVICE_PRESENT_WITH_INACTIVE_TABLE": 8,
}

func (x LogicalVolume_Attributes_State) String() string {
	return proto.EnumName(LogicalVolume_Attributes_State_name, int32(x))
}

func (LogicalVolume_Attributes_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0, 3}
}

type LogicalVolume_Attributes_TargetType int32

const (
	LogicalVolume_Attributes_MALFORMED_TARGET LogicalVolume_Attributes_TargetType = 0
	LogicalVolume_Attributes_MIRROR_TARGET    LogicalVolume_Attributes_TargetType = 1
	LogicalVolume_Attributes_RAID_TARGET      LogicalVolume_Attributes_TargetType = 2
	LogicalVolume_Attributes_SNAPSHOT_TARGET  LogicalVolume_Attributes_TargetType = 3
	LogicalVolume_Attributes_THIN_TARGET      LogicalVolume_Attributes_TargetType = 4
	LogicalVolume_Attributes_UNKNOWN_TARGET   LogicalVolume_Attributes_TargetType = 5
	LogicalVolume_Attributes_VIRTUAL_TARGET   LogicalVolume_Attributes_TargetType = 6
)

var LogicalVolume_Attributes_TargetType_name = map[int32]string{
	0: "MALFORMED_TARGET",
	1: "MIRROR_TARGET",
	2: "RAID_TARGET",
	3: "SNAPSHOT_TARGET",
	4: "THIN_TARGET",
	5: "UNKNOWN_TARGET",
	6: "VIRTUAL_TARGET",
}

var LogicalVolume_Attributes_TargetType_value = map[string]int32{
	"MALFORMED_TARGET": 0,
	"MIRROR_TARGET":    1,
	"RAID_TARGET":      2,
	"SNAPSHOT_TARGET":  3,
	"THIN_TARGET":      4,
	"UNKNOWN_TARGET":   5,
	"VIRTUAL_TARGET":   6,
}

func (x LogicalVolume_Attributes_TargetType) String() string {
	return proto.EnumName(LogicalVolume_Attributes_TargetType_name, int32(x))
}

func (LogicalVolume_Attributes_TargetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0, 4}
}

type LogicalVolume_Attributes_Health int32

const (
	LogicalVolume_Attributes_MALFORMED_HEALTH LogicalVolume_Attributes_Health = 0
	LogicalVolume_Attributes_OK               LogicalVolume_Attributes_Health = 1
	LogicalVolume_Attributes_PARTIAL          LogicalVolume_Attributes_Health = 2
	LogicalVolume_Attributes_REFRESH_NEEDED   LogicalVolume_Attributes_Health = 3
	LogicalVolume_Attributes_MISMATCHES_EXIST LogicalVolume_Attributes_Health = 4
	LogicalVolume_Attributes_WRITEMOSTLY      LogicalVolume_Attributes_Health = 5
)

var LogicalVolume_Attributes_Health_name = map[int32]string{
	0: "MALFORMED_HEALTH",
	1: "OK",
	2: "PARTIAL",
	3: "REFRESH_NEEDED",
	4: "MISMATCHES_EXIST",
	5: "WRITEMOSTLY",
}

var LogicalVolume_Attributes_Health_value = map[string]int32{
	"MALFORMED_HEALTH": 0,
	"OK":               1,
	"PARTIAL":          2,
	"REFRESH_NEEDED":   3,
	"MISMATCHES_EXIST": 4,
	"WRITEMOSTLY":      5,
}

func (x LogicalVolume_Attributes_Health) String() string {
	return proto.EnumName(LogicalVolume_Attributes_Health_name, int32(x))
}

func (LogicalVolume_Attributes_Health) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0, 5}
}

type LogicalVolume struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint64                    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Uuid                 string                    `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Attributes           *LogicalVolume_Attributes `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	CopyPercent          string                    `protobuf:"bytes,5,opt,name=copy_percent,json=copyPercent,proto3" json:"copy_percent,omitempty"`
	ActualDevMajorNumber uint32                    `protobuf:"varint,6,opt,name=actual_dev_major_number,json=actualDevMajorNumber,proto3" json:"actual_dev_major_number,omitempty"`
	ActualDevMinorNumber uint32                    `protobuf:"varint,7,opt,name=actual_dev_minor_number,json=actualDevMinorNumber,proto3" json:"actual_dev_minor_number,omitempty"`
	Tags                 []string                  `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LogicalVolume) Reset()         { *m = LogicalVolume{} }
func (m *LogicalVolume) String() string { return proto.CompactTextString(m) }
func (*LogicalVolume) ProtoMessage()    {}
func (*LogicalVolume) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0}
}

func (m *LogicalVolume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalVolume.Unmarshal(m, b)
}
func (m *LogicalVolume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalVolume.Marshal(b, m, deterministic)
}
func (m *LogicalVolume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalVolume.Merge(m, src)
}
func (m *LogicalVolume) XXX_Size() int {
	return xxx_messageInfo_LogicalVolume.Size(m)
}
func (m *LogicalVolume) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalVolume.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalVolume proto.InternalMessageInfo

func (m *LogicalVolume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LogicalVolume) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *LogicalVolume) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *LogicalVolume) GetAttributes() *LogicalVolume_Attributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *LogicalVolume) GetCopyPercent() string {
	if m != nil {
		return m.CopyPercent
	}
	return ""
}

func (m *LogicalVolume) GetActualDevMajorNumber() uint32 {
	if m != nil {
		return m.ActualDevMajorNumber
	}
	return 0
}

func (m *LogicalVolume) GetActualDevMinorNumber() uint32 {
	if m != nil {
		return m.ActualDevMinorNumber
	}
	return 0
}

func (m *LogicalVolume) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type LogicalVolume_Attributes struct {
	Type                 LogicalVolume_Attributes_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=lvm.LogicalVolume_Attributes_Type" json:"type,omitempty"`
	Permissions          LogicalVolume_Attributes_Permissions `protobuf:"varint,2,opt,name=permissions,proto3,enum=lvm.LogicalVolume_Attributes_Permissions" json:"permissions,omitempty"`
	Allocation           LogicalVolume_Attributes_Allocation  `protobuf:"varint,3,opt,name=allocation,proto3,enum=lvm.LogicalVolume_Attributes_Allocation" json:"allocation,omitempty"`
	FixedMinor           bool                                 `protobuf:"varint,4,opt,name=fixed_minor,json=fixedMinor,proto3" json:"fixed_minor,omitempty"`
	State                LogicalVolume_Attributes_State       `protobuf:"varint,5,opt,name=state,proto3,enum=lvm.LogicalVolume_Attributes_State" json:"state,omitempty"`
	Open                 bool                                 `protobuf:"varint,6,opt,name=open,proto3" json:"open,omitempty"`
	TargetType           LogicalVolume_Attributes_TargetType  `protobuf:"varint,7,opt,name=target_type,json=targetType,proto3,enum=lvm.LogicalVolume_Attributes_TargetType" json:"target_type,omitempty"`
	Zeroing              bool                                 `protobuf:"varint,8,opt,name=zeroing,proto3" json:"zeroing,omitempty"`
	Health               LogicalVolume_Attributes_Health      `protobuf:"varint,9,opt,name=health,proto3,enum=lvm.LogicalVolume_Attributes_Health" json:"health,omitempty"`
	ActivationSkipped    bool                                 `protobuf:"varint,10,opt,name=activation_skipped,json=activationSkipped,proto3" json:"activation_skipped,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *LogicalVolume_Attributes) Reset()         { *m = LogicalVolume_Attributes{} }
func (m *LogicalVolume_Attributes) String() string { return proto.CompactTextString(m) }
func (*LogicalVolume_Attributes) ProtoMessage()    {}
func (*LogicalVolume_Attributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{0, 0}
}

func (m *LogicalVolume_Attributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalVolume_Attributes.Unmarshal(m, b)
}
func (m *LogicalVolume_Attributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalVolume_Attributes.Marshal(b, m, deterministic)
}
func (m *LogicalVolume_Attributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalVolume_Attributes.Merge(m, src)
}
func (m *LogicalVolume_Attributes) XXX_Size() int {
	return xxx_messageInfo_LogicalVolume_Attributes.Size(m)
}
func (m *LogicalVolume_Attributes) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalVolume_Attributes.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalVolume_Attributes proto.InternalMessageInfo

func (m *LogicalVolume_Attributes) GetType() LogicalVolume_Attributes_Type {
	if m != nil {
		return m.Type
	}
	return LogicalVolume_Attributes_MALFORMED_TYPE
}

func (m *LogicalVolume_Attributes) GetPermissions() LogicalVolume_Attributes_Permissions {
	if m != nil {
		return m.Permissions
	}
	return LogicalVolume_Attributes_MALFORMED_PERMISSIONS
}

func (m *LogicalVolume_Attributes) GetAllocation() LogicalVolume_Attributes_Allocation {
	if m != nil {
		return m.Allocation
	}
	return LogicalVolume_Attributes_MALFORMED_ALLOCATION
}

func (m *LogicalVolume_Attributes) GetFixedMinor() bool {
	if m != nil {
		return m.FixedMinor
	}
	return false
}

func (m *LogicalVolume_Attributes) GetState() LogicalVolume_Attributes_State {
	if m != nil {
		return m.State
	}
	return LogicalVolume_Attributes_MALFORMED_STATE
}

func (m *LogicalVolume_Attributes) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *LogicalVolume_Attributes) GetTargetType() LogicalVolume_Attributes_TargetType {
	if m != nil {
		return m.TargetType
	}
	return LogicalVolume_Attributes_MALFORMED_TARGET
}

func (m *LogicalVolume_Attributes) GetZeroing() bool {
	if m != nil {
		return m.Zeroing
	}
	return false
}

func (m *LogicalVolume_Attributes) GetHealth() LogicalVolume_Attributes_Health {
	if m != nil {
		return m.Health
	}
	return LogicalVolume_Attributes_MALFORMED_HEALTH
}

func (m *LogicalVolume_Attributes) GetActivationSkipped() bool {
	if m != nil {
		return m.ActivationSkipped
	}
	return false
}

type VolumeGroup struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	FreeSize             uint64   `protobuf:"varint,3,opt,name=free_size,json=freeSize,proto3" json:"free_size,omitempty"`
	Uuid                 string   `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VolumeGroup) Reset()         { *m = VolumeGroup{} }
func (m *VolumeGroup) String() string { return proto.CompactTextString(m) }
func (*VolumeGroup) ProtoMessage()    {}
func (*VolumeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{1}
}

func (m *VolumeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VolumeGroup.Unmarshal(m, b)
}
func (m *VolumeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VolumeGroup.Marshal(b, m, deterministic)
}
func (m *VolumeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VolumeGroup.Merge(m, src)
}
func (m *VolumeGroup) XXX_Size() int {
	return xxx_messageInfo_VolumeGroup.Size(m)
}
func (m *VolumeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_VolumeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_VolumeGroup proto.InternalMessageInfo

func (m *VolumeGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VolumeGroup) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *VolumeGroup) GetFreeSize() uint64 {
	if m != nil {
		return m.FreeSize
	}
	return 0
}

func (m *VolumeGroup) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *VolumeGroup) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ListLVRequest struct {
	VolumeGroup          string   `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLVRequest) Reset()         { *m = ListLVRequest{} }
func (m *ListLVRequest) String() string { return proto.CompactTextString(m) }
func (*ListLVRequest) ProtoMessage()    {}
func (*ListLVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{2}
}

func (m *ListLVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLVRequest.Unmarshal(m, b)
}
func (m *ListLVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLVRequest.Marshal(b, m, deterministic)
}
func (m *ListLVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLVRequest.Merge(m, src)
}
func (m *ListLVRequest) XXX_Size() int {
	return xxx_messageInfo_ListLVRequest.Size(m)
}
func (m *ListLVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLVRequest proto.InternalMessageInfo

func (m *ListLVRequest) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

type ListLVReply struct {
	Volumes              []*LogicalVolume `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListLVReply) Reset()         { *m = ListLVReply{} }
func (m *ListLVReply) String() string { return proto.CompactTextString(m) }
func (*ListLVReply) ProtoMessage()    {}
func (*ListLVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{3}
}

func (m *ListLVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLVReply.Unmarshal(m, b)
}
func (m *ListLVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLVReply.Marshal(b, m, deterministic)
}
func (m *ListLVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLVReply.Merge(m, src)
}
func (m *ListLVReply) XXX_Size() int {
	return xxx_messageInfo_ListLVReply.Size(m)
}
func (m *ListLVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLVReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListLVReply proto.InternalMessageInfo

func (m *ListLVReply) GetVolumes() []*LogicalVolume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type CreateLVRequest struct {
	VolumeGroup          string   `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size                 uint64   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mirrors              uint32   `protobuf:"varint,4,opt,name=mirrors,proto3" json:"mirrors,omitempty"`
	Tags                 []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLVRequest) Reset()         { *m = CreateLVRequest{} }
func (m *CreateLVRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLVRequest) ProtoMessage()    {}
func (*CreateLVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{4}
}

func (m *CreateLVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLVRequest.Unmarshal(m, b)
}
func (m *CreateLVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLVRequest.Marshal(b, m, deterministic)
}
func (m *CreateLVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLVRequest.Merge(m, src)
}
func (m *CreateLVRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLVRequest.Size(m)
}
func (m *CreateLVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLVRequest proto.InternalMessageInfo

func (m *CreateLVRequest) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

func (m *CreateLVRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateLVRequest) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *CreateLVRequest) GetMirrors() uint32 {
	if m != nil {
		return m.Mirrors
	}
	return 0
}

func (m *CreateLVRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateLVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateLVReply) Reset()         { *m = CreateLVReply{} }
func (m *CreateLVReply) String() string { return proto.CompactTextString(m) }
func (*CreateLVReply) ProtoMessage()    {}
func (*CreateLVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{5}
}

func (m *CreateLVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLVReply.Unmarshal(m, b)
}
func (m *CreateLVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLVReply.Marshal(b, m, deterministic)
}
func (m *CreateLVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLVReply.Merge(m, src)
}
func (m *CreateLVReply) XXX_Size() int {
	return xxx_messageInfo_CreateLVReply.Size(m)
}
func (m *CreateLVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLVReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLVReply proto.InternalMessageInfo

func (m *CreateLVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type RemoveLVRequest struct {
	VolumeGroup          string   `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveLVRequest) Reset()         { *m = RemoveLVRequest{} }
func (m *RemoveLVRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveLVRequest) ProtoMessage()    {}
func (*RemoveLVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{6}
}

func (m *RemoveLVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveLVRequest.Unmarshal(m, b)
}
func (m *RemoveLVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveLVRequest.Marshal(b, m, deterministic)
}
func (m *RemoveLVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLVRequest.Merge(m, src)
}
func (m *RemoveLVRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveLVRequest.Size(m)
}
func (m *RemoveLVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLVRequest proto.InternalMessageInfo

func (m *RemoveLVRequest) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

func (m *RemoveLVRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoveLVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveLVReply) Reset()         { *m = RemoveLVReply{} }
func (m *RemoveLVReply) String() string { return proto.CompactTextString(m) }
func (*RemoveLVReply) ProtoMessage()    {}
func (*RemoveLVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{7}
}

func (m *RemoveLVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveLVReply.Unmarshal(m, b)
}
func (m *RemoveLVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveLVReply.Marshal(b, m, deterministic)
}
func (m *RemoveLVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveLVReply.Merge(m, src)
}
func (m *RemoveLVReply) XXX_Size() int {
	return xxx_messageInfo_RemoveLVReply.Size(m)
}
func (m *RemoveLVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveLVReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveLVReply proto.InternalMessageInfo

func (m *RemoveLVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type CloneLVRequest struct {
	SourceName           string   `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	DestName             string   `protobuf:"bytes,2,opt,name=dest_name,json=destName,proto3" json:"dest_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneLVRequest) Reset()         { *m = CloneLVRequest{} }
func (m *CloneLVRequest) String() string { return proto.CompactTextString(m) }
func (*CloneLVRequest) ProtoMessage()    {}
func (*CloneLVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{8}
}

func (m *CloneLVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneLVRequest.Unmarshal(m, b)
}
func (m *CloneLVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneLVRequest.Marshal(b, m, deterministic)
}
func (m *CloneLVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneLVRequest.Merge(m, src)
}
func (m *CloneLVRequest) XXX_Size() int {
	return xxx_messageInfo_CloneLVRequest.Size(m)
}
func (m *CloneLVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneLVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloneLVRequest proto.InternalMessageInfo

func (m *CloneLVRequest) GetSourceName() string {
	if m != nil {
		return m.SourceName
	}
	return ""
}

func (m *CloneLVRequest) GetDestName() string {
	if m != nil {
		return m.DestName
	}
	return ""
}

type CloneLVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloneLVReply) Reset()         { *m = CloneLVReply{} }
func (m *CloneLVReply) String() string { return proto.CompactTextString(m) }
func (*CloneLVReply) ProtoMessage()    {}
func (*CloneLVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{9}
}

func (m *CloneLVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloneLVReply.Unmarshal(m, b)
}
func (m *CloneLVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloneLVReply.Marshal(b, m, deterministic)
}
func (m *CloneLVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloneLVReply.Merge(m, src)
}
func (m *CloneLVReply) XXX_Size() int {
	return xxx_messageInfo_CloneLVReply.Size(m)
}
func (m *CloneLVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CloneLVReply.DiscardUnknown(m)
}

var xxx_messageInfo_CloneLVReply proto.InternalMessageInfo

func (m *CloneLVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type ListVGRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListVGRequest) Reset()         { *m = ListVGRequest{} }
func (m *ListVGRequest) String() string { return proto.CompactTextString(m) }
func (*ListVGRequest) ProtoMessage()    {}
func (*ListVGRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{10}
}

func (m *ListVGRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVGRequest.Unmarshal(m, b)
}
func (m *ListVGRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVGRequest.Marshal(b, m, deterministic)
}
func (m *ListVGRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVGRequest.Merge(m, src)
}
func (m *ListVGRequest) XXX_Size() int {
	return xxx_messageInfo_ListVGRequest.Size(m)
}
func (m *ListVGRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVGRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListVGRequest proto.InternalMessageInfo

type ListVGReply struct {
	VolumeGroups         []*VolumeGroup `protobuf:"bytes,1,rep,name=volume_groups,json=volumeGroups,proto3" json:"volume_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListVGReply) Reset()         { *m = ListVGReply{} }
func (m *ListVGReply) String() string { return proto.CompactTextString(m) }
func (*ListVGReply) ProtoMessage()    {}
func (*ListVGReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{11}
}

func (m *ListVGReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVGReply.Unmarshal(m, b)
}
func (m *ListVGReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVGReply.Marshal(b, m, deterministic)
}
func (m *ListVGReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVGReply.Merge(m, src)
}
func (m *ListVGReply) XXX_Size() int {
	return xxx_messageInfo_ListVGReply.Size(m)
}
func (m *ListVGReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVGReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListVGReply proto.InternalMessageInfo

func (m *ListVGReply) GetVolumeGroups() []*VolumeGroup {
	if m != nil {
		return m.VolumeGroups
	}
	return nil
}

type CreateVGRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhysicalVolume       string   `protobuf:"bytes,2,opt,name=physical_volume,json=physicalVolume,proto3" json:"physical_volume,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVGRequest) Reset()         { *m = CreateVGRequest{} }
func (m *CreateVGRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVGRequest) ProtoMessage()    {}
func (*CreateVGRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{12}
}

func (m *CreateVGRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVGRequest.Unmarshal(m, b)
}
func (m *CreateVGRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVGRequest.Marshal(b, m, deterministic)
}
func (m *CreateVGRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVGRequest.Merge(m, src)
}
func (m *CreateVGRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVGRequest.Size(m)
}
func (m *CreateVGRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVGRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVGRequest proto.InternalMessageInfo

func (m *CreateVGRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVGRequest) GetPhysicalVolume() string {
	if m != nil {
		return m.PhysicalVolume
	}
	return ""
}

func (m *CreateVGRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type CreateVGReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVGReply) Reset()         { *m = CreateVGReply{} }
func (m *CreateVGReply) String() string { return proto.CompactTextString(m) }
func (*CreateVGReply) ProtoMessage()    {}
func (*CreateVGReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{13}
}

func (m *CreateVGReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVGReply.Unmarshal(m, b)
}
func (m *CreateVGReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVGReply.Marshal(b, m, deterministic)
}
func (m *CreateVGReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVGReply.Merge(m, src)
}
func (m *CreateVGReply) XXX_Size() int {
	return xxx_messageInfo_CreateVGReply.Size(m)
}
func (m *CreateVGReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVGReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVGReply proto.InternalMessageInfo

func (m *CreateVGReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type RemoveVGRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveVGRequest) Reset()         { *m = RemoveVGRequest{} }
func (m *RemoveVGRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveVGRequest) ProtoMessage()    {}
func (*RemoveVGRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{14}
}

func (m *RemoveVGRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveVGRequest.Unmarshal(m, b)
}
func (m *RemoveVGRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveVGRequest.Marshal(b, m, deterministic)
}
func (m *RemoveVGRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveVGRequest.Merge(m, src)
}
func (m *RemoveVGRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveVGRequest.Size(m)
}
func (m *RemoveVGRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveVGRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveVGRequest proto.InternalMessageInfo

func (m *RemoveVGRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RemoveVGReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveVGReply) Reset()         { *m = RemoveVGReply{} }
func (m *RemoveVGReply) String() string { return proto.CompactTextString(m) }
func (*RemoveVGReply) ProtoMessage()    {}
func (*RemoveVGReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{15}
}

func (m *RemoveVGReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveVGReply.Unmarshal(m, b)
}
func (m *RemoveVGReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveVGReply.Marshal(b, m, deterministic)
}
func (m *RemoveVGReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveVGReply.Merge(m, src)
}
func (m *RemoveVGReply) XXX_Size() int {
	return xxx_messageInfo_RemoveVGReply.Size(m)
}
func (m *RemoveVGReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveVGReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveVGReply proto.InternalMessageInfo

func (m *RemoveVGReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type AddTagLVRequest struct {
	VolumeGroup          string   `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagLVRequest) Reset()         { *m = AddTagLVRequest{} }
func (m *AddTagLVRequest) String() string { return proto.CompactTextString(m) }
func (*AddTagLVRequest) ProtoMessage()    {}
func (*AddTagLVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{16}
}

func (m *AddTagLVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagLVRequest.Unmarshal(m, b)
}
func (m *AddTagLVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagLVRequest.Marshal(b, m, deterministic)
}
func (m *AddTagLVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagLVRequest.Merge(m, src)
}
func (m *AddTagLVRequest) XXX_Size() int {
	return xxx_messageInfo_AddTagLVRequest.Size(m)
}
func (m *AddTagLVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagLVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagLVRequest proto.InternalMessageInfo

func (m *AddTagLVRequest) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

func (m *AddTagLVRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddTagLVRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type AddTagLVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddTagLVReply) Reset()         { *m = AddTagLVReply{} }
func (m *AddTagLVReply) String() string { return proto.CompactTextString(m) }
func (*AddTagLVReply) ProtoMessage()    {}
func (*AddTagLVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{17}
}

func (m *AddTagLVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddTagLVReply.Unmarshal(m, b)
}
func (m *AddTagLVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddTagLVReply.Marshal(b, m, deterministic)
}
func (m *AddTagLVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTagLVReply.Merge(m, src)
}
func (m *AddTagLVReply) XXX_Size() int {
	return xxx_messageInfo_AddTagLVReply.Size(m)
}
func (m *AddTagLVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTagLVReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddTagLVReply proto.InternalMessageInfo

func (m *AddTagLVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type RemoveTagLVRequest struct {
	VolumeGroup          string   `protobuf:"bytes,1,opt,name=volume_group,json=volumeGroup,proto3" json:"volume_group,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags                 []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTagLVRequest) Reset()         { *m = RemoveTagLVRequest{} }
func (m *RemoveTagLVRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTagLVRequest) ProtoMessage()    {}
func (*RemoveTagLVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{18}
}

func (m *RemoveTagLVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTagLVRequest.Unmarshal(m, b)
}
func (m *RemoveTagLVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTagLVRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTagLVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTagLVRequest.Merge(m, src)
}
func (m *RemoveTagLVRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTagLVRequest.Size(m)
}
func (m *RemoveTagLVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTagLVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTagLVRequest proto.InternalMessageInfo

func (m *RemoveTagLVRequest) GetVolumeGroup() string {
	if m != nil {
		return m.VolumeGroup
	}
	return ""
}

func (m *RemoveTagLVRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RemoveTagLVRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type RemoveTagLVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTagLVReply) Reset()         { *m = RemoveTagLVReply{} }
func (m *RemoveTagLVReply) String() string { return proto.CompactTextString(m) }
func (*RemoveTagLVReply) ProtoMessage()    {}
func (*RemoveTagLVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{19}
}

func (m *RemoveTagLVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTagLVReply.Unmarshal(m, b)
}
func (m *RemoveTagLVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTagLVReply.Marshal(b, m, deterministic)
}
func (m *RemoveTagLVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTagLVReply.Merge(m, src)
}
func (m *RemoveTagLVReply) XXX_Size() int {
	return xxx_messageInfo_RemoveTagLVReply.Size(m)
}
func (m *RemoveTagLVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTagLVReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTagLVReply proto.InternalMessageInfo

func (m *RemoveTagLVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type CreatePVRequest struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePVRequest) Reset()         { *m = CreatePVRequest{} }
func (m *CreatePVRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePVRequest) ProtoMessage()    {}
func (*CreatePVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{20}
}

func (m *CreatePVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePVRequest.Unmarshal(m, b)
}
func (m *CreatePVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePVRequest.Marshal(b, m, deterministic)
}
func (m *CreatePVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePVRequest.Merge(m, src)
}
func (m *CreatePVRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePVRequest.Size(m)
}
func (m *CreatePVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePVRequest proto.InternalMessageInfo

func (m *CreatePVRequest) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

type CreatePVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePVReply) Reset()         { *m = CreatePVReply{} }
func (m *CreatePVReply) String() string { return proto.CompactTextString(m) }
func (*CreatePVReply) ProtoMessage()    {}
func (*CreatePVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{21}
}

func (m *CreatePVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePVReply.Unmarshal(m, b)
}
func (m *CreatePVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePVReply.Marshal(b, m, deterministic)
}
func (m *CreatePVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePVReply.Merge(m, src)
}
func (m *CreatePVReply) XXX_Size() int {
	return xxx_messageInfo_CreatePVReply.Size(m)
}
func (m *CreatePVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePVReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePVReply proto.InternalMessageInfo

func (m *CreatePVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type RemovePVRequest struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePVRequest) Reset()         { *m = RemovePVRequest{} }
func (m *RemovePVRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePVRequest) ProtoMessage()    {}
func (*RemovePVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{22}
}

func (m *RemovePVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePVRequest.Unmarshal(m, b)
}
func (m *RemovePVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePVRequest.Marshal(b, m, deterministic)
}
func (m *RemovePVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePVRequest.Merge(m, src)
}
func (m *RemovePVRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePVRequest.Size(m)
}
func (m *RemovePVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePVRequest proto.InternalMessageInfo

func (m *RemovePVRequest) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

type RemovePVReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePVReply) Reset()         { *m = RemovePVReply{} }
func (m *RemovePVReply) String() string { return proto.CompactTextString(m) }
func (*RemovePVReply) ProtoMessage()    {}
func (*RemovePVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{23}
}

func (m *RemovePVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePVReply.Unmarshal(m, b)
}
func (m *RemovePVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePVReply.Marshal(b, m, deterministic)
}
func (m *RemovePVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePVReply.Merge(m, src)
}
func (m *RemovePVReply) XXX_Size() int {
	return xxx_messageInfo_RemovePVReply.Size(m)
}
func (m *RemovePVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePVReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePVReply proto.InternalMessageInfo

func (m *RemovePVReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type ListPVRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPVRequest) Reset()         { *m = ListPVRequest{} }
func (m *ListPVRequest) String() string { return proto.CompactTextString(m) }
func (*ListPVRequest) ProtoMessage()    {}
func (*ListPVRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{24}
}

func (m *ListPVRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPVRequest.Unmarshal(m, b)
}
func (m *ListPVRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPVRequest.Marshal(b, m, deterministic)
}
func (m *ListPVRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPVRequest.Merge(m, src)
}
func (m *ListPVRequest) XXX_Size() int {
	return xxx_messageInfo_ListPVRequest.Size(m)
}
func (m *ListPVRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPVRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPVRequest proto.InternalMessageInfo

type ListPVReply struct {
	Pvinfos              []*PVInfo `protobuf:"bytes,1,rep,name=pvinfos,proto3" json:"pvinfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListPVReply) Reset()         { *m = ListPVReply{} }
func (m *ListPVReply) String() string { return proto.CompactTextString(m) }
func (*ListPVReply) ProtoMessage()    {}
func (*ListPVReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{25}
}

func (m *ListPVReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPVReply.Unmarshal(m, b)
}
func (m *ListPVReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPVReply.Marshal(b, m, deterministic)
}
func (m *ListPVReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPVReply.Merge(m, src)
}
func (m *ListPVReply) XXX_Size() int {
	return xxx_messageInfo_ListPVReply.Size(m)
}
func (m *ListPVReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPVReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListPVReply proto.InternalMessageInfo

func (m *ListPVReply) GetPvinfos() []*PVInfo {
	if m != nil {
		return m.Pvinfos
	}
	return nil
}

type PVInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Fmt                  string   `protobuf:"bytes,3,opt,name=fmt,proto3" json:"fmt,omitempty"`
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Usize                uint64   `protobuf:"varint,5,opt,name=usize,proto3" json:"usize,omitempty"`
	Fsize                uint64   `protobuf:"varint,6,opt,name=fsize,proto3" json:"fsize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PVInfo) Reset()         { *m = PVInfo{} }
func (m *PVInfo) String() string { return proto.CompactTextString(m) }
func (*PVInfo) ProtoMessage()    {}
func (*PVInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{26}
}

func (m *PVInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PVInfo.Unmarshal(m, b)
}
func (m *PVInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PVInfo.Marshal(b, m, deterministic)
}
func (m *PVInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PVInfo.Merge(m, src)
}
func (m *PVInfo) XXX_Size() int {
	return xxx_messageInfo_PVInfo.Size(m)
}
func (m *PVInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PVInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PVInfo proto.InternalMessageInfo

func (m *PVInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PVInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *PVInfo) GetFmt() string {
	if m != nil {
		return m.Fmt
	}
	return ""
}

func (m *PVInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PVInfo) GetUsize() uint64 {
	if m != nil {
		return m.Usize
	}
	return 0
}

func (m *PVInfo) GetFsize() uint64 {
	if m != nil {
		return m.Fsize
	}
	return 0
}

type ValidateRequest struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{27}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

type ValidateReply struct {
	Validate             bool     `protobuf:"varint,1,opt,name=validate,proto3" json:"validate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateReply) Reset()         { *m = ValidateReply{} }
func (m *ValidateReply) String() string { return proto.CompactTextString(m) }
func (*ValidateReply) ProtoMessage()    {}
func (*ValidateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{28}
}

func (m *ValidateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateReply.Unmarshal(m, b)
}
func (m *ValidateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateReply.Marshal(b, m, deterministic)
}
func (m *ValidateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateReply.Merge(m, src)
}
func (m *ValidateReply) XXX_Size() int {
	return xxx_messageInfo_ValidateReply.Size(m)
}
func (m *ValidateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateReply.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateReply proto.InternalMessageInfo

func (m *ValidateReply) GetValidate() bool {
	if m != nil {
		return m.Validate
	}
	return false
}

type DestoryRequest struct {
	Block                string   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestoryRequest) Reset()         { *m = DestoryRequest{} }
func (m *DestoryRequest) String() string { return proto.CompactTextString(m) }
func (*DestoryRequest) ProtoMessage()    {}
func (*DestoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{29}
}

func (m *DestoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestoryRequest.Unmarshal(m, b)
}
func (m *DestoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestoryRequest.Marshal(b, m, deterministic)
}
func (m *DestoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestoryRequest.Merge(m, src)
}
func (m *DestoryRequest) XXX_Size() int {
	return xxx_messageInfo_DestoryRequest.Size(m)
}
func (m *DestoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestoryRequest proto.InternalMessageInfo

func (m *DestoryRequest) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

type DestoryReply struct {
	CommandOutput        string   `protobuf:"bytes,1,opt,name=command_output,json=commandOutput,proto3" json:"command_output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestoryReply) Reset()         { *m = DestoryReply{} }
func (m *DestoryReply) String() string { return proto.CompactTextString(m) }
func (*DestoryReply) ProtoMessage()    {}
func (*DestoryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_8cc5677814b58357, []int{30}
}

func (m *DestoryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestoryReply.Unmarshal(m, b)
}
func (m *DestoryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestoryReply.Marshal(b, m, deterministic)
}
func (m *DestoryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestoryReply.Merge(m, src)
}
func (m *DestoryReply) XXX_Size() int {
	return xxx_messageInfo_DestoryReply.Size(m)
}
func (m *DestoryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DestoryReply.DiscardUnknown(m)
}

var xxx_messageInfo_DestoryReply proto.InternalMessageInfo

func (m *DestoryReply) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

func init() {
	proto.RegisterEnum("lvm.LogicalVolume_Attributes_Type", LogicalVolume_Attributes_Type_name, LogicalVolume_Attributes_Type_value)
	proto.RegisterEnum("lvm.LogicalVolume_Attributes_Permissions", LogicalVolume_Attributes_Permissions_name, LogicalVolume_Attributes_Permissions_value)
	proto.RegisterEnum("lvm.LogicalVolume_Attributes_Allocation", LogicalVolume_Attributes_Allocation_name, LogicalVolume_Attributes_Allocation_value)
	proto.RegisterEnum("lvm.LogicalVolume_Attributes_State", LogicalVolume_Attributes_State_name, LogicalVolume_Attributes_State_value)
	proto.RegisterEnum("lvm.LogicalVolume_Attributes_TargetType", LogicalVolume_Attributes_TargetType_name, LogicalVolume_Attributes_TargetType_value)
	proto.RegisterEnum("lvm.LogicalVolume_Attributes_Health", LogicalVolume_Attributes_Health_name, LogicalVolume_Attributes_Health_value)
	proto.RegisterType((*LogicalVolume)(nil), "lvm.LogicalVolume")
	proto.RegisterType((*LogicalVolume_Attributes)(nil), "lvm.LogicalVolume.Attributes")
	proto.RegisterType((*VolumeGroup)(nil), "lvm.VolumeGroup")
	proto.RegisterType((*ListLVRequest)(nil), "lvm.ListLVRequest")
	proto.RegisterType((*ListLVReply)(nil), "lvm.ListLVReply")
	proto.RegisterType((*CreateLVRequest)(nil), "lvm.CreateLVRequest")
	proto.RegisterType((*CreateLVReply)(nil), "lvm.CreateLVReply")
	proto.RegisterType((*RemoveLVRequest)(nil), "lvm.RemoveLVRequest")
	proto.RegisterType((*RemoveLVReply)(nil), "lvm.RemoveLVReply")
	proto.RegisterType((*CloneLVRequest)(nil), "lvm.CloneLVRequest")
	proto.RegisterType((*CloneLVReply)(nil), "lvm.CloneLVReply")
	proto.RegisterType((*ListVGRequest)(nil), "lvm.ListVGRequest")
	proto.RegisterType((*ListVGReply)(nil), "lvm.ListVGReply")
	proto.RegisterType((*CreateVGRequest)(nil), "lvm.CreateVGRequest")
	proto.RegisterType((*CreateVGReply)(nil), "lvm.CreateVGReply")
	proto.RegisterType((*RemoveVGRequest)(nil), "lvm.RemoveVGRequest")
	proto.RegisterType((*RemoveVGReply)(nil), "lvm.RemoveVGReply")
	proto.RegisterType((*AddTagLVRequest)(nil), "lvm.AddTagLVRequest")
	proto.RegisterType((*AddTagLVReply)(nil), "lvm.AddTagLVReply")
	proto.RegisterType((*RemoveTagLVRequest)(nil), "lvm.RemoveTagLVRequest")
	proto.RegisterType((*RemoveTagLVReply)(nil), "lvm.RemoveTagLVReply")
	proto.RegisterType((*CreatePVRequest)(nil), "lvm.CreatePVRequest")
	proto.RegisterType((*CreatePVReply)(nil), "lvm.CreatePVReply")
	proto.RegisterType((*RemovePVRequest)(nil), "lvm.RemovePVRequest")
	proto.RegisterType((*RemovePVReply)(nil), "lvm.RemovePVReply")
	proto.RegisterType((*ListPVRequest)(nil), "lvm.ListPVRequest")
	proto.RegisterType((*ListPVReply)(nil), "lvm.ListPVReply")
	proto.RegisterType((*PVInfo)(nil), "lvm.PVInfo")
	proto.RegisterType((*ValidateRequest)(nil), "lvm.ValidateRequest")
	proto.RegisterType((*ValidateReply)(nil), "lvm.ValidateReply")
	proto.RegisterType((*DestoryRequest)(nil), "lvm.DestoryRequest")
	proto.RegisterType((*DestoryReply)(nil), "lvm.DestoryReply")
}

func init() { proto.RegisterFile("lvm.proto", fileDescriptor_8cc5677814b58357) }

var fileDescriptor_8cc5677814b58357 = []byte{
	// 1744 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdb, 0x6e, 0xe3, 0xc6,
	0x19, 0xb6, 0xce, 0xd2, 0x4f, 0x4b, 0x1a, 0x4f, 0xbc, 0x89, 0xe2, 0xb4, 0x5d, 0x97, 0x49, 0x1a,
	0x07, 0x6d, 0x16, 0x85, 0xd3, 0x5d, 0x20, 0x68, 0x8b, 0x82, 0x15, 0x67, 0x25, 0x62, 0x29, 0x92,
	0x18, 0xd2, 0xda, 0x1a, 0x28, 0x30, 0xa5, 0x25, 0xda, 0xab, 0x46, 0x12, 0x55, 0x89, 0x12, 0xea,
	0xbd, 0xec, 0x45, 0x2e, 0x7a, 0x5d, 0xf4, 0xbd, 0xfa, 0x0e, 0x7d, 0x8e, 0xa2, 0x98, 0x19, 0x1e,
	0x65, 0xc7, 0xb5, 0xd1, 0xf6, 0x6e, 0xe6, 0xfb, 0x4f, 0xdf, 0xfc, 0x87, 0x19, 0x4a, 0xd0, 0x9a,
	0xef, 0x16, 0x2f, 0x56, 0xeb, 0x30, 0x0a, 0x71, 0x65, 0xbe, 0x5b, 0xa8, 0x7f, 0x47, 0xd0, 0x36,
	0xc3, 0x9b, 0xd9, 0xc4, 0x9f, 0x8f, 0xc3, 0xf9, 0x76, 0x11, 0x60, 0x0c, 0xd5, 0xa5, 0xbf, 0x08,
	0x7a, 0xa5, 0xd3, 0xd2, 0x59, 0x8b, 0x8a, 0x35, 0xc7, 0x36, 0xb3, 0xf7, 0x41, 0xaf, 0x7c, 0x5a,
	0x3a, 0xab, 0x52, 0xb1, 0xe6, 0xd8, 0x76, 0x3b, 0x9b, 0xf6, 0x2a, 0x52, 0x8f, 0xaf, 0xf1, 0xaf,
	0x01, 0xfc, 0x28, 0x5a, 0xcf, 0xae, 0xb6, 0x51, 0xb0, 0xe9, 0x55, 0x4f, 0x4b, 0x67, 0xca, 0xf9,
	0x0f, 0x5f, 0xf0, 0x90, 0x85, 0x18, 0x2f, 0xb4, 0x54, 0x89, 0xe6, 0x0c, 0xf0, 0x8f, 0xe1, 0x70,
	0x12, 0xae, 0x6e, 0xd9, 0x2a, 0x58, 0x4f, 0x82, 0x65, 0xd4, 0xab, 0x09, 0xd7, 0x0a, 0xc7, 0x1c,
	0x09, 0xe1, 0x97, 0xf0, 0x91, 0x3f, 0x89, 0xb6, 0xfe, 0x9c, 0x4d, 0x83, 0x1d, 0x5b, 0xf8, 0x7f,
	0x0c, 0xd7, 0x6c, 0xb9, 0x5d, 0x5c, 0x05, 0xeb, 0x5e, 0xfd, 0xb4, 0x74, 0xd6, 0xa6, 0xc7, 0x52,
	0xac, 0x07, 0xbb, 0x11, 0x17, 0x5a, 0x42, 0xb6, 0x6f, 0x36, 0x5b, 0x66, 0x66, 0x8d, 0x7d, 0x33,
	0x2e, 0x8c, 0xcd, 0x30, 0x54, 0x23, 0xff, 0x66, 0xd3, 0x6b, 0x9e, 0x56, 0xf8, 0x19, 0xf9, 0xfa,
	0xe4, 0x9f, 0x6d, 0x80, 0x8c, 0x3f, 0x7e, 0x05, 0xd5, 0xe8, 0x76, 0x25, 0xd3, 0xd5, 0x39, 0x57,
	0x1f, 0x3c, 0xec, 0x0b, 0xef, 0x76, 0x15, 0x50, 0xa1, 0x8f, 0xdf, 0x80, 0xb2, 0x0a, 0xd6, 0x8b,
	0xd9, 0x66, 0x33, 0x0b, 0x97, 0x1b, 0x91, 0xd9, 0xce, 0xf9, 0x97, 0x0f, 0x9b, 0x3b, 0x99, 0x01,
	0xcd, 0x5b, 0xe3, 0x21, 0x80, 0x3f, 0x9f, 0x87, 0x13, 0x3f, 0x9a, 0x85, 0x4b, 0x51, 0x91, 0xce,
	0xf9, 0xd9, 0xc3, 0xbe, 0xb4, 0x54, 0x9f, 0xe6, 0x6c, 0xf1, 0x73, 0x50, 0xae, 0x67, 0x7f, 0x0e,
	0xa6, 0x32, 0x47, 0xa2, 0x84, 0x4d, 0x0a, 0x02, 0x12, 0x89, 0xc1, 0xdf, 0x40, 0x6d, 0x13, 0xf9,
	0x51, 0x20, 0x8a, 0xd3, 0x39, 0xff, 0xf4, 0xe1, 0x28, 0x2e, 0x57, 0xa5, 0xd2, 0x82, 0x67, 0x33,
	0x5c, 0x05, 0x4b, 0x51, 0xa8, 0x26, 0x15, 0x6b, 0x6c, 0x80, 0x12, 0xf9, 0xeb, 0x9b, 0x20, 0x62,
	0x22, 0x8b, 0x8d, 0xc7, 0x50, 0xf7, 0x84, 0x81, 0xc8, 0x25, 0x44, 0xe9, 0x1a, 0xf7, 0xa0, 0xf1,
	0x3e, 0x58, 0x87, 0xb3, 0xe5, 0x4d, 0xaf, 0x29, 0x22, 0x24, 0x5b, 0xfc, 0x2b, 0xa8, 0xbf, 0x0b,
	0xfc, 0x79, 0xf4, 0xae, 0xd7, 0x12, 0xfe, 0x3f, 0x7b, 0xd8, 0xff, 0x50, 0xe8, 0xd2, 0xd8, 0x06,
	0x7f, 0x05, 0xd8, 0x9f, 0x44, 0xb3, 0x9d, 0x48, 0x10, 0xdb, 0x7c, 0x3b, 0x5b, 0xad, 0x82, 0x69,
	0x0f, 0x44, 0x88, 0xa3, 0x4c, 0xe2, 0x4a, 0x81, 0xfa, 0xaf, 0x32, 0x54, 0x05, 0x1f, 0x0c, 0x9d,
	0x91, 0x66, 0xbe, 0xb6, 0xe9, 0x88, 0xe8, 0xcc, 0xbb, 0x74, 0x08, 0x3a, 0xc0, 0x87, 0xd0, 0x1c,
	0x19, 0x94, 0xda, 0x94, 0xe8, 0xa8, 0x84, 0x3f, 0x86, 0x67, 0xc9, 0x8e, 0xbd, 0x35, 0xbc, 0xa1,
	0x7d, 0xe1, 0x31, 0xf7, 0xd2, 0xea, 0xa3, 0x32, 0x06, 0xa8, 0xdb, 0xd4, 0x18, 0x18, 0x16, 0xaa,
	0xe0, 0x53, 0xf8, 0x81, 0x5c, 0x0b, 0x25, 0x36, 0x22, 0x74, 0x60, 0x58, 0x03, 0xe6, 0x5a, 0x9a,
	0xe3, 0x0e, 0x6d, 0x0f, 0x55, 0x71, 0x13, 0xaa, 0x54, 0x33, 0x74, 0x54, 0xc3, 0xcf, 0xe0, 0x88,
	0xaf, 0x8a, 0xee, 0xea, 0x3c, 0x6e, 0xaa, 0xde, 0xc0, 0xc7, 0x80, 0xee, 0x38, 0x69, 0x62, 0x05,
	0x1a, 0xce, 0x98, 0x8d, 0xec, 0x31, 0x41, 0x2d, 0x4e, 0x7e, 0x6c, 0x50, 0xef, 0x42, 0x33, 0x99,
	0xa4, 0x88, 0x00, 0x7f, 0x08, 0x38, 0xc1, 0x44, 0x0c, 0x63, 0xa4, 0x0d, 0x08, 0x52, 0xf0, 0x09,
	0x7c, 0x98, 0xed, 0x19, 0x8f, 0x6a, 0xbf, 0x96, 0x81, 0x0f, 0x71, 0x07, 0x40, 0xda, 0x33, 0xd3,
	0x1e, 0xa0, 0x36, 0x0f, 0x7d, 0x61, 0xe9, 0x84, 0xb2, 0xbe, 0x6d, 0x8d, 0x09, 0x75, 0x0d, 0xdb,
	0x42, 0x1d, 0xce, 0xdf, 0x1b, 0x1a, 0x16, 0xea, 0xe2, 0x36, 0xb4, 0xf8, 0x8a, 0x39, 0xb6, 0x6d,
	0x22, 0xc4, 0x69, 0xa4, 0x5b, 0xa6, 0x6b, 0x9e, 0x86, 0x8e, 0xf0, 0x8f, 0xe0, 0x44, 0x84, 0xb3,
	0x29, 0xcb, 0x64, 0x23, 0xe2, 0x69, 0x42, 0x8e, 0xd5, 0x3f, 0x80, 0x92, 0x1b, 0x14, 0x91, 0xe4,
	0xb4, 0x0c, 0x0e, 0xa1, 0x23, 0xc3, 0xe5, 0x51, 0x5d, 0x74, 0xc0, 0x83, 0xbd, 0xa5, 0x86, 0x47,
	0xb4, 0xdf, 0x9a, 0x04, 0x95, 0xf8, 0x96, 0x12, 0x4d, 0x67, 0xb6, 0x65, 0x5e, 0xa2, 0x32, 0xee,
	0xc1, 0x71, 0xba, 0x65, 0x5a, 0xdf, 0x33, 0xc6, 0x9a, 0xc7, 0xe9, 0x56, 0xd4, 0x7f, 0x94, 0x00,
	0xb2, 0xf9, 0xe1, 0x8a, 0x59, 0x04, 0xcd, 0x34, 0xed, 0xbe, 0x54, 0x14, 0xe5, 0xd6, 0xac, 0xcb,
	0xb7, 0x43, 0x42, 0xb9, 0xff, 0x0e, 0x40, 0xdf, 0xb6, 0x3c, 0x63, 0x70, 0x61, 0x5f, 0xb8, 0xa8,
	0xcc, 0xe3, 0x19, 0xd6, 0x90, 0x70, 0x06, 0x3a, 0xaa, 0xe0, 0x16, 0xd4, 0xfa, 0xa6, 0x61, 0x0d,
	0x50, 0x95, 0x57, 0xdf, 0xb2, 0xe9, 0x48, 0x33, 0x51, 0x0d, 0x7f, 0x00, 0xdd, 0xc4, 0x07, 0x33,
	0xed, 0xfe, 0x1b, 0xa2, 0xa3, 0x3a, 0x2f, 0x73, 0xe6, 0x2a, 0x81, 0x45, 0x61, 0x53, 0x8f, 0x09,
	0xda, 0xc4, 0x08, 0x0e, 0x85, 0xe3, 0x04, 0x69, 0xe1, 0x23, 0x68, 0x4b, 0xff, 0x09, 0x04, 0xea,
	0x77, 0x65, 0xa8, 0x89, 0x69, 0xe5, 0x01, 0xb3, 0xe3, 0xb8, 0x9e, 0xe6, 0xf1, 0xc6, 0x05, 0xa8,
	0x8b, 0x14, 0xc4, 0x79, 0x72, 0x2f, 0x5c, 0x87, 0x58, 0x3a, 0xd1, 0x51, 0x59, 0x06, 0x1d, 0x6b,
	0xa6, 0xa1, 0x67, 0xdd, 0x54, 0xe1, 0x55, 0x4a, 0xd1, 0x44, 0x39, 0xdf, 0xb2, 0x1f, 0xc3, 0xb3,
	0x64, 0x27, 0x3a, 0x9a, 0xb0, 0xd7, 0x9a, 0x61, 0x12, 0xde, 0xc3, 0x9f, 0xc2, 0xf3, 0xbb, 0x26,
	0x45, 0xa5, 0x3a, 0x3e, 0x83, 0xcf, 0x46, 0x9a, 0xe3, 0x10, 0x9d, 0xe9, 0x64, 0x6c, 0xf4, 0x09,
	0x73, 0x28, 0x71, 0x89, 0xe5, 0xa5, 0x9d, 0xef, 0xf1, 0xaa, 0xba, 0xa8, 0x81, 0xbf, 0x82, 0x2f,
	0xbf, 0x5f, 0x93, 0x19, 0x96, 0x3c, 0x97, 0xd4, 0x47, 0x4d, 0xf5, 0x6f, 0x25, 0x80, 0xec, 0x86,
	0x11, 0xb3, 0x92, 0x4d, 0xb1, 0x46, 0x07, 0xc4, 0x43, 0x07, 0x3c, 0x81, 0x71, 0x5b, 0xc7, 0x50,
	0x09, 0x77, 0x41, 0x11, 0x6d, 0x19, 0x03, 0x65, 0x9e, 0xc7, 0x94, 0x7c, 0x0c, 0x56, 0xb8, 0x96,
	0x68, 0xda, 0x18, 0xa8, 0xf2, 0x0e, 0xbf, 0xb0, 0xde, 0x58, 0xf6, 0xdb, 0x14, 0xab, 0xe5, 0x87,
	0x2f, 0xc6, 0xea, 0xea, 0x12, 0xea, 0xf2, 0x5e, 0x2a, 0x32, 0x1a, 0x12, 0xcd, 0xf4, 0x86, 0xe8,
	0x00, 0xd7, 0xa1, 0x6c, 0xbf, 0x41, 0x25, 0x31, 0xc5, 0x1a, 0xf5, 0x0c, 0xcd, 0x44, 0x65, 0xee,
	0x88, 0x92, 0xd7, 0x94, 0xb8, 0x43, 0x66, 0x11, 0xa2, 0x8b, 0x36, 0xe3, 0xe6, 0x86, 0x3b, 0xd2,
	0xbc, 0xfe, 0x90, 0xb8, 0x8c, 0xfc, 0xce, 0x70, 0x39, 0x8d, 0x2e, 0x28, 0x62, 0x14, 0x46, 0xb6,
	0xeb, 0x99, 0x97, 0xa8, 0xa6, 0xbe, 0x07, 0x45, 0xde, 0x8c, 0x83, 0x75, 0xb8, 0x5d, 0x3d, 0xfa,
	0xab, 0xe0, 0x13, 0x68, 0x5d, 0xaf, 0x83, 0x80, 0x09, 0x41, 0x45, 0x08, 0x9a, 0x1c, 0x70, 0xf3,
	0x9f, 0x0c, 0xd5, 0xdc, 0x27, 0x43, 0xf2, 0xc4, 0xd6, 0xb2, 0x27, 0x56, 0x3d, 0x87, 0xb6, 0x39,
	0xdb, 0x44, 0xe6, 0x98, 0x06, 0x7f, 0xda, 0x06, 0x9b, 0x88, 0x7f, 0x18, 0xec, 0x04, 0x19, 0x76,
	0xc3, 0xd9, 0xc4, 0x2c, 0x94, 0x5d, 0x46, 0x50, 0xfd, 0x25, 0x28, 0x89, 0xcd, 0x6a, 0x7e, 0x8b,
	0x7f, 0x06, 0x0d, 0x29, 0xdd, 0xf4, 0x4a, 0xa7, 0x95, 0x33, 0xe5, 0x1c, 0xdf, 0xbd, 0xf3, 0x69,
	0xa2, 0xa2, 0xfe, 0xb5, 0x04, 0xdd, 0xfe, 0x3a, 0xf0, 0xa3, 0xe0, 0x29, 0x31, 0xd3, 0xa4, 0x94,
	0xef, 0x49, 0x4a, 0x25, 0x97, 0x94, 0x1e, 0x34, 0x16, 0xb3, 0xf5, 0x3a, 0x5c, 0xcb, 0x6f, 0xa2,
	0x36, 0x4d, 0xb6, 0xf7, 0x9e, 0xfe, 0x15, 0xb4, 0x33, 0x2e, 0xfc, 0x2c, 0x9f, 0x43, 0x67, 0x12,
	0x2e, 0x16, 0xfe, 0x72, 0xca, 0xc2, 0x6d, 0xb4, 0xda, 0x46, 0x31, 0x97, 0x76, 0x8c, 0xda, 0x02,
	0x54, 0x87, 0xd0, 0xa5, 0xc1, 0x22, 0xdc, 0xfd, 0xd7, 0x67, 0xe0, 0x0c, 0x32, 0x4f, 0x4f, 0x60,
	0x60, 0x41, 0xa7, 0x3f, 0x0f, 0x97, 0x39, 0x02, 0xcf, 0x41, 0xd9, 0x84, 0xdb, 0xf5, 0x24, 0x60,
	0xb9, 0xee, 0x01, 0x09, 0x59, 0x3c, 0x5d, 0x9f, 0x40, 0x6b, 0x1a, 0x6c, 0x22, 0x96, 0xe3, 0xd0,
	0xe4, 0x00, 0x17, 0xaa, 0x2f, 0xe1, 0x30, 0xf5, 0xf7, 0x04, 0x1a, 0x5d, 0xd9, 0x3e, 0xe3, 0x41,
	0xcc, 0x42, 0xd5, 0x65, 0x6f, 0x70, 0x80, 0xbb, 0x79, 0x09, 0xed, 0x7c, 0x56, 0x92, 0x0e, 0x41,
	0xa2, 0x43, 0x72, 0x4d, 0x4f, 0x0f, 0x73, 0x89, 0xda, 0xa8, 0x57, 0x49, 0x8f, 0xa4, 0x8e, 0xef,
	0x9d, 0x8a, 0x2f, 0xa0, 0xbb, 0x7a, 0x77, 0xbb, 0xe1, 0x6d, 0xc6, 0xa4, 0x7d, 0x7c, 0xae, 0x4e,
	0x02, 0x67, 0x1f, 0xda, 0xa2, 0xf6, 0x95, 0xfb, 0x6a, 0x9f, 0x70, 0x7d, 0xe4, 0x91, 0x3f, 0x4f,
	0x6a, 0xff, 0x20, 0xb7, 0xac, 0xb0, 0x4f, 0x74, 0xff, 0x7b, 0xe8, 0x6a, 0xd3, 0xa9, 0xe7, 0xdf,
	0xfc, 0x2f, 0xc6, 0xe3, 0xbe, 0x43, 0x67, 0xde, 0x9f, 0xc0, 0x8a, 0x01, 0x96, 0xa7, 0xf9, 0x7f,
	0x11, 0xfb, 0x06, 0x50, 0x21, 0xc0, 0x13, 0xb8, 0x7d, 0x91, 0x34, 0x8b, 0x93, 0x12, 0x3b, 0x86,
	0xda, 0xd5, 0x3c, 0x9c, 0x7c, 0x1b, 0x1b, 0xc8, 0x4d, 0x56, 0x71, 0xe7, 0xc9, 0x01, 0x24, 0xb7,
	0x47, 0x04, 0xc8, 0x14, 0x9f, 0x3e, 0x45, 0xa9, 0x7b, 0xf5, 0x17, 0x72, 0x8a, 0x32, 0x37, 0x8d,
	0xd5, 0x6e, 0xb6, 0xbc, 0x0e, 0x93, 0xf9, 0x51, 0xc4, 0xfc, 0x38, 0x63, 0x63, 0x79, 0x1d, 0xd2,
	0x44, 0xa6, 0xfe, 0xa5, 0x04, 0x75, 0x89, 0x7d, 0xdf, 0x1b, 0x22, 0x9e, 0x84, 0x72, 0xee, 0x49,
	0x40, 0x50, 0xb9, 0x5e, 0x44, 0xf1, 0x0f, 0x4b, 0xbe, 0x4c, 0x2f, 0xd5, 0x6a, 0xee, 0x52, 0x3d,
	0x86, 0xda, 0x56, 0x80, 0x35, 0x01, 0xca, 0x0d, 0x47, 0xaf, 0x05, 0x5a, 0x97, 0xa8, 0xd8, 0xf0,
	0x64, 0x8d, 0xfd, 0xf9, 0x6c, 0xca, 0x7f, 0x8c, 0x3c, 0x98, 0xac, 0x9f, 0x42, 0x3b, 0x53, 0xe4,
	0xa7, 0x3c, 0x81, 0xe6, 0x2e, 0x06, 0x84, 0x66, 0x93, 0xa6, 0x7b, 0xf5, 0x27, 0xd0, 0xd1, 0x83,
	0x4d, 0x14, 0xae, 0x6f, 0x1f, 0x76, 0xfa, 0x12, 0x0e, 0x53, 0xbd, 0xc7, 0x17, 0xe0, 0xfc, 0xbb,
	0x3a, 0x54, 0xcc, 0xf1, 0x08, 0xff, 0x1c, 0xea, 0xf2, 0x65, 0xc3, 0xf1, 0x1b, 0x96, 0x7f, 0x1a,
	0x4f, 0x50, 0x01, 0x5b, 0xcd, 0x6f, 0xd5, 0x03, 0xfc, 0x0a, 0x9a, 0xc9, 0x0b, 0x82, 0x8f, 0x85,
	0x7c, 0xef, 0x71, 0x3b, 0xc1, 0x7b, 0x68, 0x6a, 0x97, 0xdc, 0xfb, 0xb1, 0xdd, 0xde, 0x83, 0x12,
	0xdb, 0x15, 0x1e, 0x07, 0xf5, 0x00, 0x7f, 0x0d, 0x8d, 0xf8, 0x9e, 0xc6, 0x1f, 0x48, 0xc7, 0x85,
	0x57, 0xe0, 0xe4, 0xa8, 0x08, 0xa6, 0xc1, 0x92, 0xa9, 0x8f, 0x83, 0xed, 0x5d, 0x31, 0x71, 0xb0,
	0xc2, 0xd5, 0xa0, 0x1e, 0xe0, 0xdf, 0x80, 0x92, 0x1b, 0x4a, 0xfc, 0x51, 0x8e, 0x51, 0xc1, 0xfa,
	0xd9, 0x5d, 0x81, 0x74, 0x10, 0xe7, 0x73, 0x3c, 0xc8, 0xe5, 0x33, 0xbd, 0x36, 0x73, 0xf9, 0x8c,
	0xef, 0xc8, 0x7c, 0x3e, 0xc7, 0x83, 0x42, 0x3e, 0x33, 0x2b, 0xbc, 0x87, 0xee, 0xe5, 0xf3, 0x3f,
	0xd8, 0x15, 0xee, 0xe4, 0x7c, 0x3c, 0xa7, 0x58, 0x3f, 0xe7, 0xde, 0xfa, 0x39, 0x77, 0xeb, 0xe7,
	0x14, 0xeb, 0xe7, 0xdc, 0x5b, 0x3f, 0x67, 0x3f, 0x23, 0x4e, 0xbe, 0xc3, 0x9c, 0x7b, 0x3a, 0xac,
	0x10, 0x29, 0x99, 0x93, 0x38, 0xd2, 0xde, 0x7c, 0xc5, 0x91, 0x0a, 0xc3, 0x24, 0x3b, 0x25, 0x1e,
	0x85, 0xb8, 0x53, 0x8a, 0x03, 0x14, 0x77, 0x4a, 0x7e, 0x5a, 0xd4, 0x83, 0xab, 0xba, 0xf8, 0xbf,
	0xea, 0xeb, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x03, 0xef, 0x2e, 0x7e, 0xbc, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LVMClient is the client API for LVM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LVMClient interface {
	ListLV(ctx context.Context, in *ListLVRequest, opts ...grpc.CallOption) (*ListLVReply, error)
	CreateLV(ctx context.Context, in *CreateLVRequest, opts ...grpc.CallOption) (*CreateLVReply, error)
	RemoveLV(ctx context.Context, in *RemoveLVRequest, opts ...grpc.CallOption) (*RemoveLVReply, error)
	CloneLV(ctx context.Context, in *CloneLVRequest, opts ...grpc.CallOption) (*CloneLVReply, error)
	AddTagLV(ctx context.Context, in *AddTagLVRequest, opts ...grpc.CallOption) (*AddTagLVReply, error)
	RemoveTagLV(ctx context.Context, in *RemoveTagLVRequest, opts ...grpc.CallOption) (*RemoveTagLVReply, error)
	ListVG(ctx context.Context, in *ListVGRequest, opts ...grpc.CallOption) (*ListVGReply, error)
	CreateVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*CreateVGReply, error)
	RemoveVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*RemoveVGReply, error)
	CreatePV(ctx context.Context, in *CreatePVRequest, opts ...grpc.CallOption) (*CreatePVReply, error)
	RemovePV(ctx context.Context, in *RemovePVRequest, opts ...grpc.CallOption) (*RemovePVReply, error)
	ListPV(ctx context.Context, in *ListPVRequest, opts ...grpc.CallOption) (*ListPVReply, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateReply, error)
	Destory(ctx context.Context, in *DestoryRequest, opts ...grpc.CallOption) (*DestoryReply, error)
}

type lVMClient struct {
	cc *grpc.ClientConn
}

func NewLVMClient(cc *grpc.ClientConn) LVMClient {
	return &lVMClient{cc}
}

func (c *lVMClient) ListLV(ctx context.Context, in *ListLVRequest, opts ...grpc.CallOption) (*ListLVReply, error) {
	out := new(ListLVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/ListLV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CreateLV(ctx context.Context, in *CreateLVRequest, opts ...grpc.CallOption) (*CreateLVReply, error) {
	out := new(CreateLVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/CreateLV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveLV(ctx context.Context, in *RemoveLVRequest, opts ...grpc.CallOption) (*RemoveLVReply, error) {
	out := new(RemoveLVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/RemoveLV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CloneLV(ctx context.Context, in *CloneLVRequest, opts ...grpc.CallOption) (*CloneLVReply, error) {
	out := new(CloneLVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/CloneLV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) AddTagLV(ctx context.Context, in *AddTagLVRequest, opts ...grpc.CallOption) (*AddTagLVReply, error) {
	out := new(AddTagLVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/AddTagLV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveTagLV(ctx context.Context, in *RemoveTagLVRequest, opts ...grpc.CallOption) (*RemoveTagLVReply, error) {
	out := new(RemoveTagLVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/RemoveTagLV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) ListVG(ctx context.Context, in *ListVGRequest, opts ...grpc.CallOption) (*ListVGReply, error) {
	out := new(ListVGReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/ListVG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CreateVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*CreateVGReply, error) {
	out := new(CreateVGReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/CreateVG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemoveVG(ctx context.Context, in *CreateVGRequest, opts ...grpc.CallOption) (*RemoveVGReply, error) {
	out := new(RemoveVGReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/RemoveVG", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) CreatePV(ctx context.Context, in *CreatePVRequest, opts ...grpc.CallOption) (*CreatePVReply, error) {
	out := new(CreatePVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/CreatePV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) RemovePV(ctx context.Context, in *RemovePVRequest, opts ...grpc.CallOption) (*RemovePVReply, error) {
	out := new(RemovePVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/RemovePV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) ListPV(ctx context.Context, in *ListPVRequest, opts ...grpc.CallOption) (*ListPVReply, error) {
	out := new(ListPVReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/ListPV", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateReply, error) {
	out := new(ValidateReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lVMClient) Destory(ctx context.Context, in *DestoryRequest, opts ...grpc.CallOption) (*DestoryReply, error) {
	out := new(DestoryReply)
	err := c.cc.Invoke(ctx, "/lvm.LVM/Destory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LVMServer is the server API for LVM service.
type LVMServer interface {
	ListLV(context.Context, *ListLVRequest) (*ListLVReply, error)
	CreateLV(context.Context, *CreateLVRequest) (*CreateLVReply, error)
	RemoveLV(context.Context, *RemoveLVRequest) (*RemoveLVReply, error)
	CloneLV(context.Context, *CloneLVRequest) (*CloneLVReply, error)
	AddTagLV(context.Context, *AddTagLVRequest) (*AddTagLVReply, error)
	RemoveTagLV(context.Context, *RemoveTagLVRequest) (*RemoveTagLVReply, error)
	ListVG(context.Context, *ListVGRequest) (*ListVGReply, error)
	CreateVG(context.Context, *CreateVGRequest) (*CreateVGReply, error)
	RemoveVG(context.Context, *CreateVGRequest) (*RemoveVGReply, error)
	CreatePV(context.Context, *CreatePVRequest) (*CreatePVReply, error)
	RemovePV(context.Context, *RemovePVRequest) (*RemovePVReply, error)
	ListPV(context.Context, *ListPVRequest) (*ListPVReply, error)
	Validate(context.Context, *ValidateRequest) (*ValidateReply, error)
	Destory(context.Context, *DestoryRequest) (*DestoryReply, error)
}

// UnimplementedLVMServer can be embedded to have forward compatible implementations.
type UnimplementedLVMServer struct {
}

func (*UnimplementedLVMServer) ListLV(ctx context.Context, req *ListLVRequest) (*ListLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLV not implemented")
}
func (*UnimplementedLVMServer) CreateLV(ctx context.Context, req *CreateLVRequest) (*CreateLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLV not implemented")
}
func (*UnimplementedLVMServer) RemoveLV(ctx context.Context, req *RemoveLVRequest) (*RemoveLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveLV not implemented")
}
func (*UnimplementedLVMServer) CloneLV(ctx context.Context, req *CloneLVRequest) (*CloneLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloneLV not implemented")
}
func (*UnimplementedLVMServer) AddTagLV(ctx context.Context, req *AddTagLVRequest) (*AddTagLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTagLV not implemented")
}
func (*UnimplementedLVMServer) RemoveTagLV(ctx context.Context, req *RemoveTagLVRequest) (*RemoveTagLVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTagLV not implemented")
}
func (*UnimplementedLVMServer) ListVG(ctx context.Context, req *ListVGRequest) (*ListVGReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVG not implemented")
}
func (*UnimplementedLVMServer) CreateVG(ctx context.Context, req *CreateVGRequest) (*CreateVGReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVG not implemented")
}
func (*UnimplementedLVMServer) RemoveVG(ctx context.Context, req *CreateVGRequest) (*RemoveVGReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVG not implemented")
}
func (*UnimplementedLVMServer) CreatePV(ctx context.Context, req *CreatePVRequest) (*CreatePVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePV not implemented")
}
func (*UnimplementedLVMServer) RemovePV(ctx context.Context, req *RemovePVRequest) (*RemovePVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemovePV not implemented")
}
func (*UnimplementedLVMServer) ListPV(ctx context.Context, req *ListPVRequest) (*ListPVReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPV not implemented")
}
func (*UnimplementedLVMServer) Validate(ctx context.Context, req *ValidateRequest) (*ValidateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (*UnimplementedLVMServer) Destory(ctx context.Context, req *DestoryRequest) (*DestoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destory not implemented")
}

func RegisterLVMServer(s *grpc.Server, srv LVMServer) {
	s.RegisterService(&_LVM_serviceDesc, srv)
}

func _LVM_ListLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).ListLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/ListLV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).ListLV(ctx, req.(*ListLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CreateLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CreateLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/CreateLV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CreateLV(ctx, req.(*CreateLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/RemoveLV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveLV(ctx, req.(*RemoveLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CloneLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloneLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CloneLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/CloneLV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CloneLV(ctx, req.(*CloneLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_AddTagLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).AddTagLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/AddTagLV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).AddTagLV(ctx, req.(*AddTagLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveTagLV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTagLVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveTagLV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/RemoveTagLV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveTagLV(ctx, req.(*RemoveTagLVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_ListVG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).ListVG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/ListVG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).ListVG(ctx, req.(*ListVGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CreateVG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CreateVG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/CreateVG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CreateVG(ctx, req.(*CreateVGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemoveVG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemoveVG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/RemoveVG",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemoveVG(ctx, req.(*CreateVGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_CreatePV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).CreatePV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/CreatePV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).CreatePV(ctx, req.(*CreatePVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_RemovePV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).RemovePV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/RemovePV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).RemovePV(ctx, req.(*RemovePVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_ListPV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).ListPV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/ListPV",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).ListPV(ctx, req.(*ListPVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LVM_Destory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LVMServer).Destory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lvm.LVM/Destory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LVMServer).Destory(ctx, req.(*DestoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LVM_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lvm.LVM",
	HandlerType: (*LVMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListLV",
			Handler:    _LVM_ListLV_Handler,
		},
		{
			MethodName: "CreateLV",
			Handler:    _LVM_CreateLV_Handler,
		},
		{
			MethodName: "RemoveLV",
			Handler:    _LVM_RemoveLV_Handler,
		},
		{
			MethodName: "CloneLV",
			Handler:    _LVM_CloneLV_Handler,
		},
		{
			MethodName: "AddTagLV",
			Handler:    _LVM_AddTagLV_Handler,
		},
		{
			MethodName: "RemoveTagLV",
			Handler:    _LVM_RemoveTagLV_Handler,
		},
		{
			MethodName: "ListVG",
			Handler:    _LVM_ListVG_Handler,
		},
		{
			MethodName: "CreateVG",
			Handler:    _LVM_CreateVG_Handler,
		},
		{
			MethodName: "RemoveVG",
			Handler:    _LVM_RemoveVG_Handler,
		},
		{
			MethodName: "CreatePV",
			Handler:    _LVM_CreatePV_Handler,
		},
		{
			MethodName: "RemovePV",
			Handler:    _LVM_RemovePV_Handler,
		},
		{
			MethodName: "ListPV",
			Handler:    _LVM_ListPV_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _LVM_Validate_Handler,
		},
		{
			MethodName: "Destory",
			Handler:    _LVM_Destory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lvm.proto",
}
